baseURL = "https://jiangtiezhu.github.io/"
languageCode = "zh-cn"
title = "铁柱的赛博后花园"
theme = "stack"

[pagination]
pagerSize = 5
relativeURLs = false
canonifyURLs = true
[params]
mainSections = ["medical", "tech", "galgame", "life", "about"]
enableRobotsTXT = true
[sitemap]
changefreq = "weekly"
priority = 0.8
filename = "sitemap.xml"
